name: Generate-ascii

on: push

jobs:
    ascii-job:
        runs-on: ubuntu-latest
        steps:
          - name: checkout repo
            uses: actions/checkout@v4

          - name: list
            run: ls
          
          - name: Execute the script
            run: ./script.sh
